<a href="https://colab.research.google.com/github/kalyanram0542/mypython/blob/master/iris_classification_random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2955 sha256=4e3b878723b5aef156842a92cd9c2434981878e6341f174016116503319714aa
  Stored in directory: /root/.cache/pip/wheels/f8/e0/3d/9d0c2020c44a519b9f02ab4fa6d2a4a996c98d79ab2f569fa1
Successfully built sklearn


# Import Librearies

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

Load *Iris* Dataset

[Click here for DataSets](https://scikit-learn.org/stable/datasets.html)

In [ ]:
iris= datasets.load_iris()

In [ ]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

input features

In [ ]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
X=iris.data
Y=iris.target

In [ ]:
X.shape

(150, 4)

In [ ]:
Y.shape

(150,)

## Build Classification model using Random Forest

In [ ]:
clf=RandomForestClassifier()

In [ ]:
clf.fit(X,Y)

RandomForestClassifier()

In [ ]:
print(clf.feature_importances_)

[0.1188471  0.02366886 0.42579412 0.43168992]


In [ ]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
print(clf.predict(X[[0]]))

['setosa']


In [ ]:
print(clf.predict_proba(X[[0]]))

[[1. 0. 0.]]


In [ ]:
print(clf.predict_log_proba(X[[0]]))

[[  0. -inf -inf]]


/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_forest.py:910: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)


In [ ]:
clf.fit(iris.data,iris.target_names[iris.target])

RandomForestClassifier()

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)

In [ ]:
x_train.shape, y_train.shape

((120, 4), (120,))

In [ ]:
x_test.shape, y_test.shape

((30, 4), (30,))

In [ ]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
print(clf.predict(X[[0]]))

[0]


In [ ]:
print(clf.predict_proba(X[[0]]))

[[1. 0. 0.]]


In [ ]:
print(clf.predict(x_test))

[0 0 1 0 2 0 1 0 1 0 0 2 1 1 1 1 1 0 1 2 1 1 2 2 2 0 2 1 0 2]


In [ ]:
print(y_test)

[0 0 1 0 2 0 1 0 1 0 0 2 1 1 1 1 2 0 1 2 1 1 2 2 2 0 2 1 0 2]


In [ ]:
print(clf.score(x_test,y_test))

0.9666666666666667
